#!/usr/bin/env Rscript
#
# roxygen2 oracle driver for arity's roxygen-oracle harness
# (tests/roxygen_oracle.rs). NOT part of the Cargo build.
#
# roxygen2 turns `#'` blocks into `.Rd`; this script exposes that as a
# differential oracle. It reads from stdin and writes to stdout; diagnostics go
# to stderr and a non-zero exit means "could not process" (the Rust harness then
# records the case as skipped, never a hard failure).
#
# Operations (argv[1]):
#   block-to-tree   stdin = R source (roxygen blocks + code)
#                   stdout = canonical Rd-tree S-expression, one line per topic
#   block-to-rd     stdin = R source; stdout = raw Rd text per topic (debugging)
#   rd-to-tree      stdin = Rd text; stdout = canonical Rd-tree S-expression
#
# The canonical serialization (rd_to_canonical) is what makes the comparison
# robust: it parses Rd with tools::parse_Rd and drops everything cosmetic ---
# srcref/srcfile attributes, the `% Generated by roxygen2`/`% Please edit`
# COMMENT header (and any Rd comment), and insignificant TEXT whitespace --- so a
# diff reflects real structural divergence, not wrapping or spacing. The body of
# \examples is replaced with a placeholder: arity intentionally reformats the R
# inside @examples (Tenet 1), which changes that text but not the documentation's
# meaning, and is covered by the R formatter's own tests.

suppressWarnings(suppressMessages({
  library(roxygen2)
}))

args <- commandArgs(trailingOnly = TRUE)
op <- if (length(args) >= 1) args[[1]] else "block-to-tree"

read_stdin <- function() {
  con <- file("stdin", "r")
  on.exit(close(con))
  paste(readLines(con, warn = FALSE), collapse = "\n")
}

# --- canonical Rd-tree serialization --------------------------------------

encode_text <- function(s) {
  s <- gsub("\\", "\\\\", s, fixed = TRUE)
  s <- gsub("\"", "\\\"", s, fixed = TRUE)
  s <- gsub("\n", "\\n", s, fixed = TRUE)
  paste0("\"", s, "\"")
}

norm_ws <- function(s) {
  s <- gsub("[[:space:]]+", " ", s)
  trimws(s)
}

# Serialize a sequence of sibling nodes, coalescing adjacent TEXT runs into a
# single normalized TEXT atom. This is what makes prose wrapping irrelevant:
# parse_Rd splits a paragraph at physical newlines into separate TEXT nodes (with
# "\n" TEXT nodes between), and roxygen2 itself only soft-wraps prose --- no
# semantic break is inserted --- so a paragraph must canonicalize identically
# regardless of how it was line-wrapped. COMMENT nodes are dropped.
emit_text <- function(buf) {
  t <- norm_ws(paste(buf, collapse = ""))
  if (nzchar(t)) paste0("(TEXT ", encode_text(t), ")") else ""
}

node_tag <- function(nd) {
  tag <- attr(nd, "Rd_tag")
  if (is.null(tag)) "TEXT" else tag
}

# A genuine prose text leaf: a character vector tagged TEXT. parse_Rd also tags
# brace-group *argument wrappers* (which are lists) as TEXT --- those are NOT
# prose and must never be coalesced with siblings (e.g. \item{term}{def} has two
# such groups), so the is.list() guard is load-bearing.
is_text_leaf <- function(nd) {
  !is.list(nd) && identical(node_tag(nd), "TEXT")
}

serialize_children <- function(nodes) {
  out <- character(0)
  i <- 1L
  n <- length(nodes)
  while (i <= n) {
    tag <- node_tag(nodes[[i]])
    if (identical(tag, "COMMENT")) {
      i <- i + 1L
      next
    }
    if (is_text_leaf(nodes[[i]])) {
      # Consume the maximal run of adjacent prose TEXT leaves (ignoring COMMENTs)
      # and emit it as one coalesced atom, so line-wrapping never affects output.
      segs <- character(0)
      while (i <= n) {
        if (is_text_leaf(nodes[[i]])) {
          segs <- c(segs, paste(unlist(nodes[[i]]), collapse = ""))
        } else if (!identical(node_tag(nodes[[i]]), "COMMENT")) {
          break
        }
        i <- i + 1L
      }
      s <- emit_text(segs)
      if (nzchar(s)) out <- c(out, s)
      next
    }
    s <- serialize_node(nodes[[i]])
    if (nzchar(s)) out <- c(out, s)
    i <- i + 1L
  }
  out
}

serialize_node <- function(node) {
  tag <- node_tag(node)

  if (identical(tag, "COMMENT")) {
    return("")
  }

  # \examples body is reformatted R; compare only its presence, not content.
  if (identical(tag, "\\examples")) {
    return("(\\examples ...)")
  }

  if (is.list(node)) {
    parts <- serialize_children(node)
    inner <- paste(parts, collapse = " ")
    # A brace-group argument wrapper is tagged TEXT but carries no macro name:
    # emit its content directly (grouped only when it holds more than one atom).
    if (identical(tag, "TEXT")) {
      if (length(parts) <= 1) {
        return(inner)
      }
      return(paste0("(GRP ", inner, ")"))
    }
    return(paste0("(", tag, if (nzchar(inner)) paste0(" ", inner) else "", ")"))
  }

  # Character leaf.
  if (identical(tag, "TEXT")) {
    txt <- norm_ws(paste(unlist(node), collapse = ""))
    if (!nzchar(txt)) {
      return("")
    }
    return(paste0("(TEXT ", encode_text(txt), ")"))
  }
  txt <- paste(unlist(node), collapse = "")
  if (tag %in% c("RCODE", "VERB")) {
    # Verbatim-ish: keep as-is (only encode), no whitespace collapse.
    return(paste0("(", tag, " ", encode_text(txt), ")"))
  }
  paste0("(", tag, " ", encode_text(norm_ws(txt)), ")")
}

rd_to_canonical <- function(rd_text) {
  tf <- tempfile(fileext = ".Rd")
  on.exit(unlink(tf))
  writeLines(rd_text, tf)
  rd <- tools::parse_Rd(tf)
  parts <- serialize_children(rd)
  paste0("(Rd ", paste(parts, collapse = " "), ")")
}

# --- roxygen2 block -> Rd --------------------------------------------------

block_to_topics <- function(src) {
  topics <- roc_proc_text(rd_roclet(), src)
  if (length(topics) == 0) {
    stop("roxygen2 produced no topics (block not attached to an object?)")
  }
  # Sort by topic filename for a stable, order-independent comparison.
  topics[order(names(topics))]
}

main <- function() {
  src <- read_stdin()

  if (identical(op, "rd-to-tree")) {
    cat(rd_to_canonical(src), "\n", sep = "")
    return(invisible())
  }

  topics <- block_to_topics(src)
  for (nm in names(topics)) {
    rd <- format(topics[[nm]])
    if (identical(op, "block-to-rd")) {
      cat("# ", nm, "\n", rd, "\n", sep = "")
    } else {
      # block-to-tree (default)
      cat(nm, "\t", rd_to_canonical(rd), "\n", sep = "")
    }
  }
}

tryCatch(
  main(),
  error = function(e) {
    message("roxygen_oracle: ", conditionMessage(e))
    quit(status = 2, save = "no")
  }
)
