[workspace]
members = ["crates/arity-parser", "crates/arity-formatter"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/jolars/arity"
authors = ["Johan Larsson <johan@jolars.co>"]

[package]
name = "arity"
version = "0.18.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "A language server, formatter, and linter for R"
license.workspace = true
repository.workspace = true
homepage = "https://arity.cc"
documentation = "https://arity.cc"
authors.workspace = true
include = ["/src/**/*", "/build.rs", "/README.md", "/LICENSE"]
keywords = ["r", "language-server", "formatter", "linter"]
categories = [
  "command-line-utilities",
  "text-processing",
  "parsing",
  "parser-implementations",
]

[lib]
name = "arity"

[[bin]]
name = "arity"
path = "src/main.rs"

[dependencies]
annotate-snippets = "0.12.16"
arity-formatter = { path = "crates/arity-formatter", version = "0.3.1" }
arity-parser = { path = "crates/arity-parser", version = "0.4.0" }
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6.5"
crossbeam-channel = "0.5"
env_logger = "0.11.10"
flate2 = "1.0"
globset = "0.4.18"
ignore = "0.4.26"
log = { version = "0.4.32", features = ["release_max_level_info"] }
lsp-server = "0.10"
lsp-types = "0.97"
memchr = "2.8"
mimalloc = "0.1.52"
postcard = { version = "1.1", default-features = false, features = ["use-std"] }
rayon = "1.12.0"
regex = "1.11"
rowan = "0.17.0"
salsa = "0.28.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
similar = { version = "3.1.1", features = ["text"] }
smol_str = { version = "0.3.2", features = ["serde"] }
tempfile = "3.27.0"
toml = "1.1.2"
ureq = { version = "2.12", default-features = false, features = ["tls"] }

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = [
  "cargo_bench_support",
] }
insta = "1.47.2"

[[bench]]
name = "line_index"
harness = false

[build-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
clapdown = "0.1.0"
clap_complete = "4.6.5"
clap_mangen = "0.3.0"
