//! `desc` compatibility gauge for `DESCRIPTION` formatting.
//!
//! A **soft, one-directional signal, never a gate.** It measures the fixed point
//! `desc_normalize(arity(x)) == arity(x)` — how often `desc` would leave arity's
//! output alone — rather than diffing the two head to head. Head-to-head would
//! be dominated by the differences we chose on purpose, so the number would
//! track philosophy instead of rule divergence.
//!
//! Modeled on `crates/arity-formatter/tests/air_compat.rs`, with one deliberate
//! departure: the primary measurement runs at `line-width = 75`, because that is
//! `desc`'s hard-coded `strwrap` width. Comparing at our default 80 would pin
//! the number near zero and it would track nothing. The 80 figure is reported
//! as a secondary.
//!
//! Recorded deviations, normalized away before comparing and **never** triage
//! items:
//!
//! 1. **Comments.** `desc` drops every one, even on a plain parse-and-write.
//!    Preserving them is the invariant the DCF parser exists to uphold, so
//!    column-zero comment lines are stripped from both sides.
//! 2. **Trailing space after an empty own line.** `desc` writes `Depends: \n`;
//!    we do not emit trailing whitespace.
//! 3. Trailing-newline and final-blank-line noise.
//!
//! `#[ignore]`d because it needs R plus the `desc` package: run via
//! `task desc-compat`, which regenerates `DESC_COMPAT.md`. A missing `Rscript`
//! or `desc` is a skip, never a failure.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use arity::formatter::{FormatStyle, format_description_with_style};

/// `desc`'s own `strwrap` width, so the gauge measures rules and not widths.
const DESC_LINE_WIDTH: usize = 75;

#[test]
#[ignore = "desc style gauge; run via `task desc-compat`"]
fn desc_compat_report() {
    let Some(rscript) = locate_rscript() else {
        eprintln!("desc-compat: `Rscript` not found on PATH; skipping (this is not a failure).");
        return;
    };
    let driver = manifest_path("tests/oracle/desc_compat.R");
    if !driver.is_file() {
        eprintln!("desc-compat: driver missing; skipping.");
        return;
    }

    let cases = corpus();
    if cases.is_empty() {
        eprintln!("desc-compat: empty corpus; nothing to measure.");
        return;
    }

    let at_desc_width = measure(&rscript, &driver, &cases, DESC_LINE_WIDTH);
    let at_our_width = measure(&rscript, &driver, &cases, FormatStyle::default().line_width);

    if at_desc_width.compared == 0 {
        eprintln!("desc-compat: `desc` could not process any case; skipping.");
        return;
    }

    let report = render_report(&at_desc_width, &at_our_width);
    let path = manifest_path("DESC_COMPAT.md");
    std::fs::write(&path, &report).expect("write DESC_COMPAT.md");
    eprintln!("{report}");
    eprintln!("desc-compat: wrote {}", path.display());
}

#[derive(Default)]
struct Measurement {
    width: usize,
    compared: usize,
    identical: usize,
    /// `(label, arity, desc)` for each divergence, capped for readability.
    divergences: Vec<(String, String, String)>,
}

fn measure(rscript: &Path, driver: &Path, cases: &[(String, String)], width: usize) -> Measurement {
    let style = FormatStyle {
        line_width: width,
        ..FormatStyle::default()
    };
    let mut out = Measurement {
        width,
        ..Measurement::default()
    };

    for (label, input) in cases {
        let Ok(ours) = format_description_with_style(input, style) else {
            continue;
        };
        let Some(theirs) = run_desc(rscript, driver, &ours) else {
            continue;
        };
        out.compared += 1;
        let (lhs, rhs) = (normalize(&ours), normalize(&theirs));
        if lhs == rhs {
            out.identical += 1;
        } else if out.divergences.len() < 20 {
            out.divergences.push((label.clone(), lhs, rhs));
        }
    }
    out
}

/// Strip the recorded deviations so the comparison is about layout rules.
fn normalize(text: &str) -> String {
    text.lines()
        // Deviation 1: `desc` drops comments outright.
        .filter(|line| !line.starts_with('#'))
        // Deviation 2: `desc` leaves a trailing space after an empty own line.
        .map(|line| line.trim_end())
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_report(primary: &Measurement, secondary: &Measurement) -> String {
    let pct = |m: &Measurement| {
        if m.compared == 0 {
            0.0
        } else {
            100.0 * m.identical as f64 / m.compared as f64
        }
    };

    let mut out = String::new();
    out.push_str("# `desc` compatibility\n\n");
    out.push_str(
        "Generated by `task desc-compat`. A **soft, one-directional gauge, never a\n\
         gate**: it measures the fixed point `desc_normalize(arity(x)) == arity(x)`\n\
         after normalizing away the deviations arity keeps on purpose. A divergence\n\
         caused by arity *preserving a comment* is not a divergence to fix.\n\n",
    );
    out.push_str(&format!(
        "| Width | Cases compared | `desc` leaves unchanged |\n\
         | --- | --- | --- |\n\
         | {} (`desc`'s own `strwrap` width) | {} | {} ({:.1}%) |\n\
         | {} (arity's default) | {} | {} ({:.1}%) |\n\n",
        primary.width,
        primary.compared,
        primary.identical,
        pct(primary),
        secondary.width,
        secondary.compared,
        secondary.identical,
        pct(secondary),
    ));

    out.push_str("## Recorded intentional deviations\n\n");
    out.push_str(
        "- **Comments are preserved.** `desc` drops every one, even on a plain\n  \
         parse-and-write. Normalized away above; never a triage item.\n\
         - **No trailing space after a field with an empty own line.** `desc`\n  \
         writes `Depends: `; we do not emit trailing whitespace.\n\
         - **`R` sorts first in `Depends`.** `desc` sorts it alphabetically among\n  \
         the packages, which reads as a mistake to anyone who writes R.\n\
         - **`Authors@R` is formatted as R**, by arity's own formatter rather than\n  \
         round-tripped through `deparse()`. This is the whole point of the feature.\n\n",
    );

    out.push_str("## Divergences\n\n");
    out.push_str(
        "Read each against the recorded deviations above before treating it as a\n\
         question. What is left over is the signal: a place where arity and `desc`\n\
         disagree about a rule neither of us chose to differ on.\n\n",
    );
    if primary.divergences.is_empty() {
        out.push_str("None.\n");
    } else {
        for (label, ours, theirs) in &primary.divergences {
            out.push_str(&format!("### `{label}`\n\n```diff\n"));
            for line in diff_lines(ours, theirs) {
                out.push_str(&line);
                out.push('\n');
            }
            out.push_str("```\n\n");
        }
    }
    out
}

/// A crude first-difference view. Enough to tell what kind of divergence it is;
/// the file itself is the real artifact.
fn diff_lines(ours: &str, theirs: &str) -> Vec<String> {
    let mut out = Vec::new();
    let ours: Vec<&str> = ours.lines().collect();
    let theirs: Vec<&str> = theirs.lines().collect();
    for index in 0..ours.len().max(theirs.len()) {
        match (ours.get(index), theirs.get(index)) {
            (Some(a), Some(b)) if a == b => out.push(format!("  {a}")),
            (a, b) => {
                if let Some(a) = a {
                    out.push(format!("- {a}"));
                }
                if let Some(b) = b {
                    out.push(format!("+ {b}"));
                }
            }
        }
        if out.len() > 40 {
            out.push("  ...".to_string());
            break;
        }
    }
    out
}

/// The committed fixtures plus any real packages `DESC_COMPAT_CORPUS` points at.
fn corpus() -> Vec<(String, String)> {
    let mut cases = Vec::new();
    collect(
        &mut cases,
        &manifest_path("crates/arity-formatter/tests/fixtures/dcf"),
        "expected.dcf",
        "fixture",
    );
    collect(
        &mut cases,
        &manifest_path("tests/fixtures/rindex"),
        "DESCRIPTION",
        "rindex",
    );
    if let Ok(dir) = std::env::var("DESC_COMPAT_CORPUS") {
        collect(&mut cases, Path::new(&dir), "DESCRIPTION", "corpus");
    }
    cases
}

fn collect(cases: &mut Vec<(String, String)>, root: &Path, file_name: &str, tag: &str) {
    let Ok(entries) = std::fs::read_dir(root) else {
        return;
    };
    let mut found: Vec<PathBuf> = entries
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path().join(file_name))
        .filter(|path| path.is_file())
        .collect();
    found.sort();
    for path in found {
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let label = path
            .parent()
            .and_then(|p| p.file_name())
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        cases.push((format!("{tag}/{label}"), text));
    }
}

fn manifest_path(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn locate_rscript() -> Option<PathBuf> {
    if let Ok(path) = std::env::var("ARITY_RSCRIPT") {
        return Some(PathBuf::from(path));
    }
    Command::new("Rscript")
        .arg("--version")
        .output()
        .map(|out| out.status.success())
        .unwrap_or(false)
        .then(|| PathBuf::from("Rscript"))
}

fn run_desc(rscript: &Path, driver: &Path, input: &str) -> Option<String> {
    let mut child = Command::new(rscript)
        .arg(driver)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    child.stdin.as_mut()?.write_all(input.as_bytes()).ok()?;
    let out = child.wait_with_output().ok()?;
    out.status
        .success()
        .then(|| String::from_utf8_lossy(&out.stdout).into_owned())
}
