[package]
name = "arity-formatter"
version = "0.3.1"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Deterministic, rule-based formatter for the R language"
license.workspace = true
repository.workspace = true
homepage = "https://arity.cc"
documentation = "https://docs.rs/arity-formatter"
authors.workspace = true
include = ["/src/**/*", "/README.md", "/CHANGELOG.md"]
keywords = ["r", "formatter", "tidyverse"]
categories = ["development-tools", "text-processing"]

[dependencies]
arity-parser = { path = "../arity-parser", version = "0.4.0" }
rowan = "0.17.0"
schemars = { version = "1.2.1", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
insta = "1.48.0"
tempfile = "3.27.0"

[features]
default = []
serde = ["dep:serde"]
schema = ["serde", "dep:schemars"]
