#!/usr/bin/env Rscript
#
# Dump the exported names of the top CRAN packages to a single sectioned text
# file at src/semantic/cran/exports.txt. The Rust side `include_str!`s this to
# build the `BundledPackages` symbol provider, which lets `undefined-symbol`
# resolve names from `library()`-attached packages without those packages being
# installed locally.
#
# The package *set* comes from scripts/cran_top_packages.txt, the top-N CRAN
# packages by download count (regenerate it with scripts/rank_cran_downloads.sh,
# which ranks from the RStudio/Posit CRAN logs). This script reads that list and
# dumps the exported names of every listed package that is installed; packages
# that are not installed are warned about and skipped.
#
# Names only (no formals, no help) - those stay with the local on-disk harvest,
# which is version-exact. This file is an approximate "latest" snapshot.
#
# This script runs by hand / in CI, not at build time:
#
#     scripts/rank_cran_downloads.sh    # refresh the package list (optional)
#     Rscript scripts/dump_cran_symbols.R
#
# Install the listed packages first for complete coverage. The CI workflow
# (.github/workflows/cran-symbols.yml) installs the set from binaries and opens
# a PR with the regenerated file.

list_file <- file.path("scripts", "cran_top_packages.txt")
out_file <- file.path("src", "semantic", "cran", "exports.txt")

lines <- trimws(readLines(list_file, warn = FALSE))
packages <- lines[nzchar(lines) & !startsWith(lines, "#")]
packages <- sort(unique(packages))

installed <- rownames(installed.packages())
missing <- setdiff(packages, installed)
present <- intersect(packages, installed)

if (length(missing) > 0) {
  warning(sprintf(
    "%d package(s) not installed, skipped: %s",
    length(missing), paste(missing, collapse = ", ")
  ), call. = FALSE, immediate. = TRUE)
}

dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)

con <- file(out_file, open = "wt")
on.exit(close(con))

writeLines(c(
  "# Generated by scripts/dump_cran_symbols.R - do not edit by hand.",
  sprintf("# R %s; %d of %d top CRAN packages installed at generation.",
          getRversion(), length(present), length(packages)),
  ""
), con)

dump_names <- function(pkg) {
  ns <- asNamespace(pkg)
  exports <- getNamespaceExports(ns)
  lazydata <- tryCatch(
    as.character(names(.getNamespaceInfo(ns, "lazydata"))),
    error = function(e) character(0)
  )
  names <- sort(unique(c(exports, lazydata)))
  names[nzchar(names)]
}

total <- 0L
written <- 0L
failed <- character(0)
for (pkg in present) {
  # `installed.packages()` can list a package whose namespace won't load (e.g.
  # unmet dependencies); skip those instead of aborting the whole run.
  names <- tryCatch(dump_names(pkg), error = function(e) NULL)
  if (is.null(names)) {
    failed <- c(failed, pkg)
    warning(sprintf("could not load namespace for %s, skipped", pkg),
            call. = FALSE, immediate. = TRUE)
    next
  }
  writeLines(c(sprintf("[%s]", pkg), names, ""), con)
  total <- total + length(names)
  written <- written + 1L
  message(sprintf("wrote %d names for %s", length(names), pkg))
}

if (length(failed) > 0) {
  warning(sprintf("%d package(s) failed to load: %s",
                  length(failed), paste(failed, collapse = ", ")),
          call. = FALSE, immediate. = TRUE)
}

message(sprintf("wrote %d names across %d packages to %s",
                total, written, out_file))
