#!/usr/bin/env Rscript
#
# Dump the names exported by each "default" R package (the set R attaches at
# startup before any .Rprofile or library() call) to one text file per package
# under src/semantic/base_r/. The Rust side `include_str!`s these to build the
# `StaticBaseR` symbol provider.
#
# This script runs by hand, not at build time:
#
#     Rscript scripts/dump_base_symbols.R
#
# Re-run after upgrading R if the API surface of a default package shifts.

DEFAULT_PACKAGES <- c(
  "base",
  "datasets",
  "graphics",
  "grDevices",
  "methods",
  "stats",
  "utils"
)

out_dir <- file.path("src", "semantic", "base_r")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

for (pkg in DEFAULT_PACKAGES) {
  ns <- asNamespace(pkg)
  exports <- getNamespaceExports(ns)
  lazydata <- tryCatch(
    as.character(names(.getNamespaceInfo(ns, "lazydata"))),
    error = function(e) character(0)
  )
  names <- sort(unique(c(exports, lazydata)))
  out <- file.path(out_dir, paste0(pkg, ".txt"))
  writeLines(names, out)
  message(sprintf("wrote %d names to %s", length(names), out))
}

writeLines(
  c(
    sprintf("# generated by scripts/dump_base_symbols.R from R %s", getRversion()),
    DEFAULT_PACKAGES
  ),
  file.path(out_dir, "packages.txt")
)
