#!/usr/bin/env Rscript
#
# Regenerate src/lsp/color_names.rs: the static table mapping every
# grDevices::colors() name to its 8-bit RGB, consumed by the LSP document-color
# feature. The Rust side binary-searches this table, so the names MUST be sorted
# in byte order to match Rust's `str` `Ord` (e.g. "gray10" < "gray2"); `radix`
# sort gives exactly that.
#
# This script runs by hand, not at build time:
#
#     Rscript scripts/gen_colors.R
#
# Re-run after upgrading R if the palette in grDevices::colors() ever shifts.

names <- sort(grDevices::colors(), method = "radix")
rgb <- grDevices::col2rgb(names)

rows <- sprintf('    ("%s", %d, %d, %d),', names, rgb[1, ], rgb[2, ], rgb[3, ])

out <- file.path("src", "lsp", "color_names.rs")
writeLines(
  c(
    "//! @generated by scripts/gen_colors.R -- do not edit by hand.",
    "//!",
    "//! Every `grDevices::colors()` name mapped to its 8-bit RGB. Kept sorted in",
    "//! byte order (Rust `str` `Ord`) so [`lookup_named`] can binary-search it.",
    "",
    "/// The `grDevices::colors()` palette, sorted by name for binary search.",
    "pub(crate) static NAMED_COLORS: &[(&str, u8, u8, u8)] = &[",
    rows,
    "];",
    "",
    "/// The RGB for a named R color, matched case-insensitively (as base R's",
    "/// `col2rgb` resolves `\"Red\"`). `None` if the name is not in the palette.",
    "pub(crate) fn lookup_named(name: &str) -> Option<(u8, u8, u8)> {",
    "    let needle = name.to_ascii_lowercase();",
    "    let i = NAMED_COLORS",
    "        .binary_search_by(|(n, ..)| n.cmp(&needle.as_str()))",
    "        .ok()?;",
    "    let (_, r, g, b) = NAMED_COLORS[i];",
    "    Some((r, g, b))",
    "}",
    "",
    "#[cfg(test)]",
    "mod tests {",
    "    use super::*;",
    "",
    "    #[test]",
    "    fn table_is_sorted_unique_and_complete() {",
    "        assert_eq!(NAMED_COLORS.len(), 657);",
    "        assert!(",
    "            NAMED_COLORS.windows(2).all(|w| w[0].0 < w[1].0),",
    "            \"NAMED_COLORS must be strictly sorted + unique by name\",",
    "        );",
    "    }",
    "",
    "    #[test]",
    "    fn looks_up_case_insensitively() {",
    "        assert_eq!(lookup_named(\"red\"), Some((255, 0, 0)));",
    "        assert_eq!(lookup_named(\"Red\"), Some((255, 0, 0)));",
    "        assert_eq!(lookup_named(\"RED\"), Some((255, 0, 0)));",
    "        assert_eq!(lookup_named(\"white\"), Some((255, 255, 255)));",
    "        assert_eq!(lookup_named(\"black\"), Some((0, 0, 0)));",
    "        assert_eq!(lookup_named(\"grey\"), lookup_named(\"gray\"));",
    "        assert_eq!(lookup_named(\"notacolor\"), None);",
    "    }",
    "}",
    ""
  ),
  out
)

message(sprintf("wrote %d colors to %s", length(names), out))
