#!/usr/bin/env bash
#
# Rank CRAN packages by download count from the RStudio/Posit CRAN logs
# (http://cran-logs.rstudio.com) and write the top-N package names to
# scripts/cran_top_packages.txt as a reproducible snapshot.
#
# The cranlogs /top API caps at 100 packages, so for a wider bundle we go to the
# raw daily logs, which list every download. We stream each day's gzipped CSV
# through awk (counts live in a ~30k-key hash, no large temp files) and sum
# across several days for a stable ranking.
#
#     scripts/rank_cran_downloads.sh [N] [DAYS]
#
# N defaults to 500, DAYS to the 7 most recent available log days. This feeds
# scripts/dump_cran_symbols.R, which dumps the listed packages' exported names.
#
# Requires: curl, gunzip, awk, sort, date (standard on CI Linux/macOS).

set -euo pipefail

N="${1:-500}"
DAYS="${2:-7}"
LIST_FILE="scripts/cran_top_packages.txt"
BASE_URL="http://cran-logs.rstudio.com"

# Collect the DAYS most recent log days that actually exist (logs lag ~1-2 days),
# scanning back up to DAYS+5 calendar days.
dates=()
probe=1
while [ "${#dates[@]}" -lt "$DAYS" ] && [ "$probe" -le "$((DAYS + 5))" ]; do
  d=$(date -u -d "-${probe} day" +%Y-%m-%d 2>/dev/null || date -u -v-"${probe}"d +%Y-%m-%d)
  year=${d%%-*}
  if curl -sfI --max-time 30 "$BASE_URL/$year/$d.csv.gz" >/dev/null 2>&1; then
    dates+=("$d")
  fi
  probe=$((probe + 1))
done

if [ "${#dates[@]}" -eq 0 ]; then
  echo "error: no CRAN log days reachable" >&2
  exit 1
fi
echo "ranking over ${#dates[@]} day(s): ${dates[*]}" >&2

ranked=$(
  for d in "${dates[@]}"; do
    year=${d%%-*}
    echo "  streaming $d ..." >&2
    curl -s --max-time 600 "$BASE_URL/$year/$d.csv.gz" | gunzip 2>/dev/null
  done | awk -F, '$1!="\"date\""{gsub(/"/,"",$7); if ($7!="") c[$7]++}
                  END{for (k in c) print c[k]"\t"k}' | sort -rn
)

{
  echo "# Generated by scripts/rank_cran_downloads.sh - do not edit by hand."
  echo "# Top $N CRAN packages by downloads, from the RStudio/Posit CRAN logs"
  echo "# ($BASE_URL), summed over: ${dates[*]}."
  echo "# One package per line. Regenerate with: scripts/rank_cran_downloads.sh"
  echo ""
  # `awk` (not `head`) consumes all input: closing the pipe early would SIGPIPE
  # the producing `echo` and, under `set -o pipefail`, fail the script.
  echo "$ranked" | awk -v n="$N" 'NR <= n { print $2 }'
} > "$LIST_FILE"

echo "wrote top $N packages to $LIST_FILE" >&2
