#!/usr/bin/env bash
#
# Rank CRAN packages by download count from the RStudio/Posit CRAN logs
# (http://cran-logs.rstudio.com) and fold the top-N into
# scripts/cran_top_packages.txt.
#
# The list is ADDITIVE: each run unions the latest top-N into the committed set
# and never removes a package by ranking. This keeps the bundled symbol set
# deterministic --- a package arity once resolved stays resolvable, so
# `undefined-symbol` never silently switches off for a file just because a
# dependency drifted out of the weekly top-N. Membership only grows; the stable
# monthly window (DAYS=30) means only sustained-popular packages earn a
# (permanent) slot, so the union converges rather than tracking weekly noise.
# Packages that disappear from CRAN are pruned separately, in
# scripts/dump_cran_symbols.R (when their exports can no longer be produced),
# never here by ranking.
#
# The cranlogs /top API caps at 100 packages, so for a wider bundle we go to the
# raw daily logs, which list every download. We stream each day's gzipped CSV
# through awk (counts live in a ~30k-key hash, no large temp files) and sum
# across the window for a stable ranking.
#
#     scripts/rank_cran_downloads.sh [N] [DAYS]
#
# N defaults to 500, DAYS to the 30 most recent available log days. The unioned
# list feeds scripts/dump_cran_symbols.R, which dumps the listed packages'
# exported names.
#
# Requires: curl, gunzip, awk, sort, date (standard on CI Linux/macOS).

set -euo pipefail

N="${1:-500}"
DAYS="${2:-30}"
LIST_FILE="scripts/cran_top_packages.txt"
BASE_URL="http://cran-logs.rstudio.com"

# Collect the DAYS most recent log days that actually exist (logs lag ~1-2 days),
# scanning back up to DAYS+5 calendar days.
dates=()
probe=1
while [ "${#dates[@]}" -lt "$DAYS" ] && [ "$probe" -le "$((DAYS + 5))" ]; do
  d=$(date -u -d "-${probe} day" +%Y-%m-%d 2>/dev/null || date -u -v-"${probe}"d +%Y-%m-%d)
  year=${d%%-*}
  if curl -sfI --max-time 30 "$BASE_URL/$year/$d.csv.gz" >/dev/null 2>&1; then
    dates+=("$d")
  fi
  probe=$((probe + 1))
done

if [ "${#dates[@]}" -eq 0 ]; then
  echo "error: no CRAN log days reachable" >&2
  exit 1
fi
echo "ranking over ${#dates[@]} day(s): ${dates[-1]} .. ${dates[0]}" >&2

ranked=$(
  for d in "${dates[@]}"; do
    year=${d%%-*}
    echo "  streaming $d ..." >&2
    curl -s --max-time 600 "$BASE_URL/$year/$d.csv.gz" | gunzip 2>/dev/null
  done | awk -F, '$1!="\"date\""{gsub(/"/,"",$7); if ($7!="") c[$7]++}
                  END{for (k in c) print c[k]"\t"k}' | sort -rn
)

# This run's fresh top-N names. `awk` (not `head`) consumes all input: closing
# the pipe early would SIGPIPE the producer and, under pipefail, fail the run.
fresh=$(echo "$ranked" | awk -v n="$N" 'NR <= n { print $2 }')

# Existing committed members (the additive part: these are never dropped here).
existing=""
if [ -f "$LIST_FILE" ]; then
  existing=$(grep -vE '^#|^[[:space:]]*$' "$LIST_FILE" || true)
fi

# Union, deduplicated and sorted deterministically (LC_ALL=C: stable, ASCII,
# case-sensitive). Sorting --- rather than appending in rank order --- means the
# committed file changes only when membership actually changes: a run that adds
# nothing produces no diff, and the workflow opens no PR.
union=$(printf '%s\n%s\n' "$existing" "$fresh" | grep -vE '^[[:space:]]*$' | LC_ALL=C sort -u)

before=$(printf '%s\n' "$existing" | grep -cvE '^[[:space:]]*$' || true)
after=$(printf '%s\n' "$union" | grep -cvE '^[[:space:]]*$' || true)
echo "members: $before -> $after (added $((after - before)) this run)" >&2

{
  echo "# Generated by scripts/rank_cran_downloads.sh - do not edit by hand."
  echo "# Bundled CRAN package set: the union of the top-N-by-downloads rankings"
  echo "# (RStudio/Posit CRAN logs, $BASE_URL) accumulated over time. Additive ---"
  echo "# a package enters when it reaches the top N and is never removed by"
  echo "# ranking (only by disappearing from CRAN). Sorted; one package per line."
  echo "# Regenerate with: scripts/rank_cran_downloads.sh"
  echo ""
  echo "$union"
} > "$LIST_FILE"

echo "wrote $after packages to $LIST_FILE" >&2
